### ISSUE TITLE
Server seems to be down

### ISSUE THREAD

**Issue by gtbwise** [Yeqzids/7timer-issues#24] opened 2024-04-23 04:45 UTC

**Comment by gtbwise** [comment] 2024-04-23 04:48
server down
server showing under construction page

geoff

**Comment by lazyandproud** [comment] 2024-04-23 06:47
only https, http://7timer.info is working. SNI or something...

**Comment by gtbwise** [comment] 2024-04-23 07:28
has HTTPS certificate expired ?

geoff

**Comment by lazyandproud** [comment] 2024-04-23 07:30
no, semms to redirect to a completly different vhost.

**Comment by gtbwise** [comment] 2024-04-23 11:33
fault might be on my sites
some links not showing /disappeared

geoff

**Comment by gtbwise** [comment] 2024-04-23 11:47
update
error not with my sites

geoff

**Comment by gtbwise** [comment] 2024-04-23 12:28
ok
http://www.7timer.info 

is resolving to

https://www.7timer.info

geoff

**Comment by Yeqzids** [comment] 2024-04-24 21:24
Hi guys -- sorry for the delay in response. This seems to be due to an outdated SSL certificate. I have put in a renewal request, and it is being processed. Let's see if it fixes things...

**Comment by gtbwise** [comment] 2024-04-25 05:34
no longer get the under construction page - get dns error message page instead
and no updates yet

geoff

**Comment by lazyandproud** [comment] 2024-04-26 15:13
seems like dns A/AAAA records are missing for www.7timer.info

 dig www.7timer.info

;; QUESTION SECTION:
;www.7timer.info.               IN      A
;; AUTHORITY SECTION:
7timer.info.            95      IN      SOA     ns-cloud-e1.googledomains.com. cloud-dns-hostmaster.google.com. 11 21600 3600 259200 300

**Comment by Yeqzids** [comment] 2024-04-26 18:43
OK -- thanks -- it now looks like this is caused by a domain migration. I have fixed the DNS records, but it may take a bit of time to take effect.

**Comment by gtbwise** [comment] 2024-04-27 04:37
all good now

thank you from the bottom of my heart

geoff

**Comment by Yeqzids** [comment] 2024-04-27 12:51
It seems all has returned to normal -- I am closing the ticket now.

**Closed as completed by Yeqzids** 2024-04-27 12:51 UTC
